# exclude SafeMath when calculating test coverage
# https://eth-brownie.readthedocs.io/en/v1.10.3/config.html#exclude_paths
reports:
  exclude_contracts:
    - SafeMath
dependencies:
  - alphachainio/chainlink-contracts@1.1.0
# automatically fetch contract sources from Etherscan
autofetch_sources: True
# set a custom mnemonic for the development network
networks:
  default: mumbai
  mumbai:
    fee: pass
wallets:
  from_key: PRIVATE_KEY
  # could also do from_mnemonic, and you'd have to change the accounts.add to accounts.from_mnemonic
compiler:
  solc:
    version: 0.7.4
    remappings:
      - '@chainlink=alphachainio/chainlink-contracts@1.1.0'
